name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: कोड चेकआउट करें
        uses: actions/checkout@v3

      - name: Node.js सेटअप करें
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: निर्भरता स्थापित करें
        run: |
          npm install

      - name: Docker इमेज बनाएं
        run: |
          docker build -t sagar592/real-project .

      - name: Docker इमेज टैग करें
        run: |
          docker tag sagar592/real-project:latest sagar592/real-project:latest

      - name: DockerHub में लॉगिन करें
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker इमेज पुश करें
        run: |
          docker push sagar592/real-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: EC2 सर्वर पर SSH के माध्यम से लॉगिन करें और Docker कंटेनर चलाएं
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull sagar592/real-project:latest
            docker stop real-project || true
            docker rm real-project || true
            docker run -d -p 80:3000 --name real-project sagar592/real-project:latest
