jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Docker build and push
        working-directory: ./backend
        run: |
          docker build -t sagar592/real-project .
          docker tag sagar592/real-project:latest sagar592/real-project:latest

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        working-directory: ./backend
        run: docker push sagar592/real-project:latest

